# Generated by Django 2.2.4 on 2019-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0002_pet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption_requests',
            name='request_no',
            field=models.AutoField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
