# Generated by Django 2.2.4 on 2019-10-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0003_auto_20191020_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoption_requests',
            old_name='request_description',
            new_name='description_message',
        ),
        migrations.RenameField(
            model_name='adoption_requests',
            old_name='requester_phone_no',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='adoption_requests',
            old_name='requester_username',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='adoption_requests',
            name='requester_email',
        ),
        migrations.RemoveField(
            model_name='adoption_requests',
            name='requester_name',
        ),
    ]
