# Generated by Django 2.2.4 on 2019-10-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0004_auto_20191020_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption_requests',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(max_length=128),
        ),
    ]
