# Generated by Django 2.2.4 on 2019-10-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0005_auto_20191020_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption_requests',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petadoption.Pet'),
            preserve_default=False,
        ),
    ]
