# Generated by Django 2.2.4 on 2019-10-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0006_adoption_requests_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.TextField(default='abc road', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='Golden Retriever', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
